openapi: 3.0.0
info:
  version: 1.0.2
  title: seers
  termsOfService: 'https://seers.io/terms/'
  contact:
    email: admin@mckinleyrice.com
    url: 'http://seers.io/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: ./logo.png
  description: |
    This is an Seers API to demonstrate features of seers API specification

    # Introduction
    This specification is intended to to be a good starting point for describing your API in It also demonstrates features of [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo) tool and 
    [seers-API](https://github.com/mckinley-and-rice/seers-api) documentation engine. So beyond the standard SewersAPI syntax we use a few 
    [vendor extensions](https://github.com/mckinley-and-rice/seers-api/blob/master/docs/redoc-vendor-extensions.md).

    ## Status header response code:
    ### Note
      * 1xx: Informational - Request received, continuing process
      * 2xx: Success - The action was successfully received, understood, and accepted
      * 3xx: Redirection - Further action must be taken in order to complete the request
      * 4xx: Client Error - The request contains bad syntax or cannot be fulfilled
      * 5xx: Server Error - The server failed to fulfill an apparently valid request
    ### Response code:
    * 200 - Success.
    * 201 - Created. Returned on successful creation of a new resource. Includes a 'Location' 
    * 202 – Accepted The client requested to create something on the server. It was accepted, but it has not been completed.
    * 203 – Non-Authoritative Information Information was transmitted, but it was not taken from the primary source.
    * 204 – No Content The request was received, but there was no data sent to the client.
    * 205 – Reset Content  Similar to 204, but the response also includes a request to update the content.
    * 206 – Partial Content Only a portion of the header content was sent to the client.
    * 207 – Multi-Status  The server passed the results of several independent operations at once
    * 301 - The requested resource has been moved permanently.
    * 302 - The requested resource has moved, but was found.
    * 304 - The requested resource has not been modified since the last time you accessed it.
    * 400 - Bad request. Data issues such as invalid JSON, etc.
    * 401 - Unauthorized. Token invalid
    * 404 - Not found. Resource not found on GET.
    * 405 - Method not allowed.
    * 406 - Not acceptable response.
    * 409 - Conflict. Duplicate data or invalid data state would occur.
    * 500 - Internal Server Error
tags:
  - name: API Status
    description: Status echo operations for server
  - name: User
    description: Operations about Doctor and Patient user
  - name: Authenticate
    description: All Operations about authentication for ALl users
  - name: Registration
    description: All Operations about authentication for ALl users
  - name: Admin User
    description: Operations about Admin user
  - name: Images
    description: Operations of Patient Images
  - name: Educational Videos
    description: Operations about educational Videos for Patients
  - name: Appointment
    description: Operations about Appointment
  - name: Sample
    description: Operations to make copy for other API
  - name: Echo
    description: Example echo operations
servers:
  - url: 'https://seersapi.mckinleyrice.com/api/v1'
paths:
  /admin':
    post:
      tags:
        - Admin User
      summary: Create Admin User
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: createAdmin
      security:
        - basic_auth: []
  '/admin/{id}':
    delete:
      tags:
        - Admin User
      summary: Delete Admin User
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteAdmin
      security:
        - basic_auth: []
    put:
      tags:
        - Admin User
      summary: Update Admin User
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: updateAdmin
      security:
        - basic_auth: []
  /appointment:
    post:
      tags:
        - Appointment
      summary: Create Appointment
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: postAppointment
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    get:
      tags:
        - Appointment
      summary: List of Appointment
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getAppointment
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  '/appointment/{id}':
    delete:
      tags:
        - Appointment
      summary: Delete Appointment
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteAppointment
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    put:
      tags:
        - Appointment
      summary: update Appointment
      description: Some description of the operation. You can use `markdown` here.
      operationId: updateAppointment
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  '/appointment/doctor/{doctorid}':
    delete:
      tags:
        - Appointment
      summary: Delete Appointment - Doctor id
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteAppointmentdoctorid
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    put:
      tags:
        - Appointment
      summary: Update Appointment  - Doctor id
      description: Some description of the operation. You can use `markdown` here.
      operationId: updateAppointmentdoctorid
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    get:
      tags:
        - Appointment
      summary: List of Appointments
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getAppointmentdoctorid
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  '/appointment/patient/{patientid}':
    delete:
      tags:
        - Appointment
      summary: Delete Appointment - Patient id
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteAppointmentpatientid
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    put:
      tags:
        - Appointment
      summary: Get server status
      description: Some description of the operation. You can use `markdown` here.
      operationId: updateAppointmentpatientid
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    get:
      tags:
        - Appointment
      summary: List of Appointment
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getAppointmentpatientid
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  /auth/authenticate:
    post:
      tags:
        - Authenticate
      summary: Authenticate User (Login)
      description: |
        (All type of user) 
      operationId: authAll
      security:
        - basic_auth: []
  /auth/logout:
    get:
      tags:
        - Authenticate
      summary: Logout
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: logoutAll
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  /echo:
    post:
      tags:
        - Echo
      summary: Echo test
      description: Receive the exact message you've sent
      operationId: echo
      security:
        - api_key: []
        - basic_auth: []
  /health:
    get:
      tags:
        - API Status
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getStatus
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  /images':
    post:
      tags:
        - Images
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: addImages
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    get:
      tags:
        - Images
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getimages
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  /register/doctor:
    post:
      tags:
        - Registration
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: registerDoctor
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  /register/patient:
    post:
      tags:
        - Registration
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: registerPatient
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  /sample:
    post:
      tags:
        - Sample
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: postSample
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    put:
      tags:
        - Sample
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: putSample
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  '/users/{username}':
    get:
      tags:
        - User
      summary: Get user by user name
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getUserByName
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    put:
      tags:
        - User
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      security:
        - main_auth:
            - 'write:users'
  /video:
    post:
      tags:
        - Educational Videos
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: postVideo
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    put:
      tags:
        - Educational Videos
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: putVideo
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  '/video/{id}':
    delete:
      tags:
        - Educational Videos
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteVideo
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://seers.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://example.com/oauth/authorize'
          tokenUrl: 'https://example.com/oauth/token'
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations
    OpenID:
      type: openIdConnect
      openIdConnectUrl: 'https://example.com/.well-known/openid-configuration'
