openapi: 3.0.0
info:
  version: 1.0.2
  title: seers
  termsOfService: 'https://seers.io/terms/'
  contact:
    email: admin@mckinleyrice.com
    url: 'http://seers.io/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: ./logo.png
  description: |
    This is an Seers API to demonstrate features of seers API specification

    # Introduction
    This specification is intended to to be a good starting point for describing your API in It also demonstrates features of [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo) tool and 
    [seers-API](https://github.com/mckinley-and-rice/seers-api) documentation engine. So beyond the standard SewersAPI syntax we use a few 
    [vendor extensions](https://github.com/mckinley-and-rice/seers-api/blob/master/docs/redoc-vendor-extensions.md).

    # Status header response code:
    500 - Internal Server Error

    401 - Unauthorized. Token invalid

    200 - OK

    404 - Not Found
tags:
  - name: Status
    description: Status echo operations for server
  - name: Echo
    description: Example echo operations
  - name: User
    description: Operations about Doctor and Patient user
  - name: Educational Videos
    description: Operations about educational Videos for Patients
  - name: Authentication
    description: All Operations about authentication for ALl users
  - name: Registration
    description: All Operations about authentication for ALl users
  - name: Admin User
    description: Operations about Admin user
servers:
  - url: 'https://seersapi.mckinleyrice.com/api/v1'
paths:
  /admin:
    post:
      tags:
        - Admin User
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: createAdmin
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    put:
      tags:
        - Admin User
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: updateAdmin
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  '/admin/{id}':
    delete:
      tags:
        - Admin User
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteAdmin
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  /auth/authenticate:
    post:
      tags:
        - Authentication
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: authAll
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  /echo:
    post:
      tags:
        - Echo
      summary: Echo test
      description: Receive the exact message you've sent
      operationId: echo
      security:
        - api_key: []
        - basic_auth: []
  /health:
    get:
      tags:
        - Status
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getStatus
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  /register/doctor:
    post:
      tags:
        - Registration
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: registerDoctor
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  /register/patient:
    post:
      tags:
        - Registration
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: registerPatient
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  '/users/{username}':
    get:
      tags:
        - User
      summary: Get user by user name
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: getUserByName
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    put:
      tags:
        - User
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      security:
        - main_auth:
            - 'write:users'
  /video:
    post:
      tags:
        - Educational Videos
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: postVideo
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
    put:
      tags:
        - Educational Videos
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: putVideo
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
  '/video/{id}':
    delete:
      tags:
        - Educational Videos
      summary: Get server status
      description: |
        Some description of the operation. 
        You can use `markdown` here.
      operationId: deleteVideo
      security:
        - main_auth:
            - 'read:users'
        - api_key: []
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://columbusx.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
